config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: [:new, :create]
  delete 'logout' => 'sessions#destroy', as: :logout
  resources :posts
  resources :comments
  get '/list_users' => 'users#list_users', as: :users_list
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :title, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_attached_file :picture,
  styles: {medium: "300x300>", thumb: "100x100>"},
  default_url: "/images/:style/missing.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
    has_many :comments
    validates :email, :name, presence: true
    validates :email, uniqueness: true

    has_attached_file :avatar,
    styles: {medium: "300x300>", thumb: "100x100>"},
    default_url: "/images/:style/missing.png"

    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize
  # I want current user and logged in available in templates for other pages and views

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # return current user or set it to what is found in cookie, only if there is one to begin with
  end

  def current_post
    @current_post ||= Post.find(session[:post_id]) if session[:post_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    unless logged_in?
      flash[:danger] = "You must be logged in to view that."
      redirect_to new_session_path
    end
  end
  # unless session ID the user ID of the "thing", then deny.... then add it to helper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      flash[:danger] = "You gotta fill out the form!"
      redirect_to post_path(@comment.post)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      flash[:danger] = "You don't have access to that..."
      redirect_to comments_path
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_path(@comment)
    else
      redirect_to edit_comment_path(@comment)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_back fallback_location: posts_path
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    # adds a new post to the user's post list
    if @post.save
      redirect_to post_path(@post)
    else
      flash[:danger] = "You gotta fill out the form!"
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    unless @post.user == current_user
      flash[:danger] = "You don't have access to that..."
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      redirect_to edit_post_path(@post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_path(current_user)
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :picture)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = "Please check all fields..."
      # user informed of incomplete form
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:danger] = "Please check all fields..."
      # user notified of incomplete form
      redirect_to new_user_path
    end
  end

  def destroy
    current_user.destroy 
    # this clears the cookie
    session[:user_id] = nil
    # this logs out the current user session
    redirect_to root_path
  end

  def list_users
    # @users = User.all
    @users = User.where("name ILIKE :query", { query: "%#{params[:query]}%"})
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :bio, :location, :zip_code, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<%= form_for @comment, :html => {class: 'edit_comment form-horizontal'} do |f| %>
<div class="row"><legend class="col-md-4 col-md-offset-4">Edit Comment:</legend></div>
<fieldset>
<div class="form-group">
        <%= f.label :title, 'Title*', class: '', placeholder: "Title" %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :body, 'Body*', class: '', placeholder: "What do you want to say?" %>
        <%= f.text_area :body, class: 'form-control' %>
    </div>

    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <%= f.submit 'Update Comment', class: 'btn btn-success', method: 'patch' %>
            <%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>
        </div>
    </div>
</fieldset>
<% end %>

app/views/comments/index.html.erb
<h1>All Comments List</h1>

<ul>
    <% @comments.each do |p| %>
        <li class="links"><%= link_to p.title, comment_path(p) %></li>
    <% end %>
</ul>

<%= link_to 'Go to All Users', users_list_path, class: 'btn btn-success btn-lg"' %>

<%= link_to 'Go to All Posts', posts_path, class: 'btn btn-success btn-lg"' %>

<%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
<h1>New Comment:</h1>
<div class="form-group">
    <%= f.label :title, 'Title*', class: '', placeholder: "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :body, 'Body*', class: '', placeholder: "What do you want to say?" %>
    <%= f.text_area :body, class: 'form-control' %>
</div>

<%= f.submit 'Add Comment', class: 'btn btn-primary' %>
<% end %>

app/views/comments/show.html.erb
<div class="card text-center">
        <div class="card-header">
                <h1><%= @comment.title %></h1>
        </div>
        <div class="card-block">
          <h4 class="card-title">Commented by: <%= link_to @comment.user.name, user_path(@comment.user) %>
            about <%= time_ago_in_words @comment.created_at %> ago</h4>
          <p class="card-text"><h2><%= @comment.body %></h2></p>
          <div class="btn btn-group">
          <%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>
          <% if current_user == @comment.user %>
          <%= link_to 'Edit Comment', edit_comment_path(@comment.id), class: 'btn btn-outline-warning btn-lg"' %>
          <% end %>
          <%= link_to 'Go back to All Users', users_list_path, class: 'btn btn-outline-success btn-lg"' %>
          <%= link_to 'Go back to All Posts', posts_path, class: 'btn btn-outline-success btn-lg"' %>
          </div>
        </div>
        <div class="card-footer text-muted">

        </div>
      </div>





<!-- show the name of the user who made the comment -->

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammetry</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico" rel="stylesheet">
    <%= favicon_link_tag 'grammetry_logo.png' %>
  </head>

  <body class="<%= "home" if current_page?(root_path) %>">
    <div class="home">
    <%= render 'layouts/partials/navbar' %>
    <%= render 'layouts/partials/flash' %>
    <%= render 'layouts/partials/modal' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/partials/footer' %>
  </div>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
    <%= value %>
</div>
<% end %>
<!-- key is the 'danger', value is the message -->

app/views/layouts/partials/_footer.html.erb
<!-- <nav class="navbar fixed-bottom navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-fixed-bottom" id="footer-text"></div>
        <ul class="navbar-nav">
            <copyright>
                &copy; Kevin C. McKenna <%= Time.now.year %>
            </copyright>
        </ul>
    </div>
</nav> -->

app/views/layouts/partials/_modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="mainModalLabel">
                <%= yield :title if content_for? :title %>&nbsp;
              </h4>
            </div>
      
            <%= yield %>
          </div>
        </div>
      </div>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand"></a><%= link_to image_tag("grammetry_logo.png", height: 40, width: 40), root_path, class: "home_logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <ul class="navbar-nav">
        <% if logged_in? %>
            <li class="nav-item active">
            <%= link_to current_user.name, user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Add Post', new_post_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: 'nav-link', method: 'delete' %>
            </li>
            <form class="form-inline my-2 my-lg-0" action="<%= users_list_path %>" method="get">
            <input name="query" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Log In', new_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item"></li>
                <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_for @post, :html => {class: 'edit_post form-horizontal'} do |f| %>
<div class="row"><legend class="col-md-4 col-md-offset-4">Edit Post:</legend></div>
<fieldset>
<div class="form-group">
        <%= f.label :title, 'Title*', class: '', placeholder: "Title" %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :body, 'Body*', class: '', placeholder: "What do you want to say?" %>
        <%= f.text_area :body, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :pic_url, 'Post Photo*', class: '', placeholder: "Put photo link here" %>
        <%= f.file_field :picture, class: 'form-control' %>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <%= f.submit 'Update Post', class: 'btn btn-success', method: 'patch' %>
            <%= link_to 'Cancel', :back, class: 'btn btn-secondary btn-md'%>
            <%= link_to 'Delete Post', post_path(current_user), class: 'btn btn-danger', method: 'delete' %>
        </div>
    </div>
</fieldset>
<% end %>

app/views/posts/index.html.erb
<div class="card text-center">
        <div class="card-header">
                <h1>All Posts List</h1>
        </div>
        <div class="card-block">
          <h4 class="card-title"></h4>
          <div class="card-text">
              <ul>
                <% @posts.each do |p| %>
                    <li class="links"><%= link_to p.title, post_path(p) %></li>
                <% end %>
            </ul>
        </div>
        </div>

        <div class="card-footer text-muted">
            <div class="btn btn-group-justified">
                <%= link_to 'Go to All Users', users_list_path, class: 'btn btn-outline-success btn-lg"' %>
                <%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>
            </div>
        </div>
      </div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<h1>Create new post:</h1>
<div class="form-group">
    <%= f.label :title, 'Title*', class: '', placeholder: "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :body, 'Body*', class: '', placeholder: "What do you want to say?" %>
    <%= f.text_area :body, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :pic_url, 'Post Photo*', class: '', placeholder: "Put photo link here" %>
    <%= f.file_field :picture, class: 'form-control' %>
</div>

<%= f.submit 'Add Post', class: 'btn btn-primary' %>
<%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>
<% end %>

app/views/posts/show.html.erb
<div class="card text-center">
        <div class="card-header">
                <h1><%= @post.title %></h1>
        </div>
        <div class="card-block">
          <h4 class="card-title"><%= image_tag @post.picture.url %></h4>
          <p class="card-text"><h2><%= @post.body %></h2></p>
          <div class="btn-group btn-group-justified">
          <%= link_to 'Back', :back, class: 'btn-group btn-group-justified btn-secondary btn-lg'%>
          <% if current_user == @post.user %>
          <%= link_to 'Edit Post', edit_post_path(@post.id), class: 'btn-group btn-group-justified btn-outline-warning btn-lg' %>
          <% end %>
          </div>
        </div>
        <div class="card-footer text-muted">
            <!-- show the name of the user who made the post -->
            Posted by: <%= link_to @post.user.name, user_path(@post.user) %>
            about <%= time_ago_in_words @post.created_at %> ago
        </div>
      </div>
<br>

<h1>Comments</h1>

<ul>
    <% @post.comments.each do |c| %>
        <li class="links"><%= link_to(c.title, comment_path(c)) %></li>
        <% if current_user == c.user %>
            <%= link_to 'Edit Comment', edit_comment_path(c.id), class: 'btn btn-outline-warning btn-sm' %>
        <% end %>
        <% if current_user == @post.user || c.user %>
        <%= link_to 'Delete Comment', comment_path(c.id), class: 'btn btn-outline-danger btn-sm', method: 'delete' %>
        <% end %>
    <% end %>
</ul>
<br>
<%= form_for @comment do |f| %>
<h1>New Comment:</h1>
<div class="form-group">
    <%= f.label :title, 'Title*', class: '', placeholder: "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :body, 'Body*', class: '', placeholder: "What do you want to say?" %>
    <%= f.text_area :body, class: 'form-control' %>
</div>
<%= f.hidden_field :post_id, value: params[:id] %>
<%= f.submit 'Add Comment', class: 'btn btn-primary' %>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user, :html => {class: 'edit_user form-horizontal'} do |f| %>
<div class="row"><legend class="col-md-4 col-md-offset-4"><h1>Modify Account:</h1></legend></div>
<fieldset>
    <div class="form-group">
        <%= f.label :name, 'Name*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :name, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :name, 'Location*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :location, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :name, 'Zip Code*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.number_field :zip_code, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :email, 'Email*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :email, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :name, 'About Me*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_area :bio, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :password, 'Password*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.password_field :password, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :avatar, 'Profile Picture', class: '' %>
        <div class="col-md-5"></div>
            <%= f.file_field :avatar, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <div class="btn btn-group">
            <%= f.submit 'Update', class: 'btn btn-outline-success', method: 'patch' %>
            <%= link_to 'Cancel', :back, class: 'btn btn-outline-secondary btn-md'%>
            <%= link_to 'Delete', user_path(current_user), class: 'btn btn-danger', method: 'delete' %>
        </div>
        </div>
    </div>
</fieldset>
<% end %>

app/views/users/index.html.erb
<div class="main_page_text">
    <p class="lead">Welcome! Connect w/ IG users and meetup for IRL photo adventures</p>
    <hr class="my-4">
    <p>It's easy and free to join. Click below to get started!</p>
    <p class="lead">
    <%= link_to 'Sign Up', new_user_path, class: 'btn btn-warning btn-lg"' %>
</div>

app/views/users/list_users.html.erb
<div class="card text-center">
        <div class="card-header">
                <h1>Grammetry Users</h1>
        </div>
        <div class="card-block">
          <h4 class="card-title">
              <ul>
                <% @users.each do |u| %>
                    <li class="links"><%= link_to u.name, user_path(u) %></li>
                <% end %>
            </ul></h4>
          <p class="card-text"></p>
        </div>
        <div class="card-footer text-muted">
            <%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>
        </div>
      </div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<h1>Create Account:</h1>
    <div class="form-group">
        <%= f.label :name, 'Name*', class: '', placeholder: "Full name" %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :location, 'Location*', class: '', size: 75 %>
        <%= f.text_field :location, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :zip_code, 'Zip Code*', class: '', maxlength: 5 %>
        <%= f.number_field :zip_code, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :email, 'Email*', class: '' %>
        <%= f.email_field :email, class: 'form-control' %>
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>

    <div class="form-group">
        <%= f.label :bio, 'About Me*', class: '' %>
        <%= f.text_field :bio, class: 'form-control' %>
        <small id="bioHelp" class="form-text text-muted">Tell us a little about yourself.</small>
    </div>

    <div class="form-group">
        <%= f.label :password, 'Password*', class: '' %>
        <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation, 'Confirm Password*', class: '' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :avatar, 'Profile Picture', class: '' %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <%= f.submit 'Create Account', class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-secondary btn-md'%>

<% end %>

app/views/users/show.html.erb
<div class="row">
<div class="col-sm-4">
    <div class="card" style="width: 20rem;">
        <img class="card-img-top" <%= image_tag @user.avatar.url(:medium) %>
        <div class="card-block">
            <h1 class="card text-center"><%= @user.name %></h1>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= @user.location %></li>
            <li class="list-group-item"><%= @user.zip_code %></li>
            <li class="list-group-item"><%= @user.bio %></li>
        </ul>
        <div class="card-block">
    </div>
</div>
</div>

<br>

<div class="col-sm-8">
    <div class="card text-center">
        <div class="card-header">
            <h1>Your Posts</h1>
        </div>
        <div class="card-block">
            <h4 class="card-title"></h4>
            <ul>
                <% @user.posts.each do |p| %>
                    <li class="links"><%= link_to(p.title, post_path(p)) %></li>
                <% end %>
            </ul>
        </div>
        <div class="card-footer text-muted">
            <div class="btn-group btn-group-justified">
                <%= link_to 'Go to All Users', users_list_path, class: 'btn btn-outline-warning btn-lg' %>
                <%= link_to 'Go to All Posts', posts_path, class: 'btn btn-outline-warning btn-lg' %>
                <%= link_to 'Go to All Comments', comments_path, class: 'btn btn-outline-warning btn-lg' %>
            </div>                        
        </div>
    </div>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>